export type IActions =
  | 'LOGIN'
  | 'LOGIN_SUCCESS'
  | 'LOGIN_FAILURE'
  | 'LOGOUT'
  | 'LOGOUT_SUCCESS'
  | 'LOGOUT_FAILURE'
  | 'FETCH_RULE'
  | 'FETCH_RULE_SUCCESS'
  | 'FETCH_RULE_FAILURE'
  | 'UPDATE_RULE'
  | 'UPDATE_RULE_SUCCESS'
  | 'UPDATE_RULE_FAILURE'
  | 'FETCH_EVENTS'
  | 'FETCH_EVENTS_SUCCESS'
  | 'FETCH_EVENTS_FAILURE'
  | 'FETCH_EVENT'
  | 'FETCH_EVENT_SUCCESS'
  | 'FETCH_EVENT_FAILURE'
  | 'UPDATE_USER'
  | 'UPDATE_GC_ACCESS_TOKEN'
  | 'UPDATE_USER_SUCCESS'
  | 'UPDATE_USER_FAILURE'
  | 'FETCH_USER'
  | 'FETCH_USER_SUCCESS'
  | 'FETCH_USER_FAILURE'
  | 'FETCH_CURRENT_PROFILE'
  | 'FETCH_CURRENT_PROFILE_SUCCESS'
  | 'FETCH_CURRENT_PROFILE_FAILURE'

export interface IAction {
  type: IActions
  payload: any
}
